version: '3'

services:

  postgres:
    container_name: postgres
    build: 
      context: ./bd
      dockerfile: Dockerfile
    image: kiribati_db_dp1:1.0
    environment:
      POSTGRES_DB: kiriweb
      POSTGRES_USER: kiriuser
      POSTGRES_PASSWORD: kiripass
    ports:
      - "5432:5432"
    restart: unless-stopped
   
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:4.28
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-kiribati@kiriweb.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-Kiripass}
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    restart: unless-stopped

 # kiribati_frontend:
 #   build:
 #     context: ./web/client
 #    dockerfile: ./Dockerfile
 #   ports:
 #     - "80:3000"
 #   container_name: kiribati_frontend
 #   stdin_open: true
 #   volumes:
 #      - ./web/client:/usr/src/app/client
 #      - /usr/src/app/client/node_modules

  kiribati_backend:
    build:
      context: ./web/server
      dockerfile: ./Dockerfile
    image: "kiribati_backend"
    volumes:
      - "./web/server/:/usr/src/app"
    ports:
      - "5000:5000"
    links:
      - postgres

  nifi:
    image: apache/nifi:latest
    container_name: nifi
    restart: always
    volumes:
      - ./nifi/:/home/nifi/
    ports:
      - 8080:8080
    
  nifi-registry:
    image: apache/nifi-registry:latest
    container_name: nifiregistry
    restart: always
    ports:
      - 18080:18080  

  metabase:
    container_name: metabase
    image: metabase/metabase:latest
    ports:
      - "3000:3000"

networks:
  default:
    driver: bridge
 
volumes:
    postgres_data:
    pgadmin:  