version: '3'

services:

  postgres:
    container_name: postgres
    build: 
      context: ./bd
      dockerfile: Dockerfile
    image: kiribati_db_dp1:1.0
    environment:
      POSTGRES_DB: kiriweb
      POSTGRES_USER: kiriuser
      POSTGRES_PASSWORD: kiripass
    ports:
      - "5432:5432"
    restart: unless-stopped
   
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:4.28
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-kiribati@kiriweb.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-Kiripass}
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    restart: unless-stopped

  kiribati_web:
    build:
      context: ./web
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    container_name: kiribati_web
    stdin_open: true
    volumes:
       - ./web/html:/var/www/html
    links:
      - postgres   
      
  metabase:
    container_name: metabase
    image: metabase/metabase:latest
    ports:
      - "3000:3000"

networks:
  default:
    driver: bridge
 
volumes:
    postgres_data:
    pgadmin:  