CREATE TABLE IF NOT EXISTS cliente(
  id_cliente int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  nombre VARCHAR ,
  apellidos VARCHAR,
  edad VARCHAR,
  genero VARCHAR,
  email VARCHAR,
  profesion VARCHAR,
  ciudad VARCHAR,
  CONSTRAINT cliente_pkey PRIMARY KEY(id_cliente)
);

CREATE TABLE consulta(
  id_consulta int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  id_cliente int,
  renta_total VARCHAR,
  disponible_alquiler VARCHAR,
  entorno_ciudad VARCHAR,
  preferencia_clima VARCHAR,
  preferencia_costevida VARCHAR,
  seguro_salud VARCHAR,
  actividad_aire_libre VARCHAR,
  importancia_seguridad VARCHAR,
  CONSTRAINT id_cliente_fkey FOREIGN KEY(id_cliente) REFERENCES cliente(id_cliente),
  CONSTRAINT id_consulta_pkey PRIMARY KEY(id_consulta)
);

CREATE TABLE resultado(
  id_resultado int NOT NULL NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  id_consulta int,
  resultado varchar,
  CONSTRAINT id_consulta_fkey FOREIGN KEY(id_consulta) REFERENCES consulta(id_consulta),
  CONSTRAINT id_resultado_pkey PRIMARY KEY(id_resultado)
);

CREATE TABLE feedback_resultado(
  id_feedback_resultado int NOT NULL NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  id_resultado int,
  feedback VARCHAR, 
  CONSTRAINT id_resultado_fkey FOREIGN KEY(id_resultado) REFERENCES resultado(id_resultado),
  CONSTRAINT id_feedback_resultado_pkey PRIMARY KEY(id_feedback_resultado)
);

CREATE TABLE kiribati_dataset(
  id_ciudad INT NOT NULL NOT NULL GENERATED BY DEFAULT AS IDENTITY,
   ciudad                             VARCHAR,
  cuantia_media_arrendamiento        INTEGER  NOT NULL,
  indice_ipc                         VARCHAR NOT NULL,
  tasa_de_criminalidad               DATE  NOT NULL,
  profesionales_de_atencion_primaria VARCHAR NOT NULL,
  temperatura                        VARCHAR NOT NULL,
  cultura                            INTEGER  NOT NULL,
  deporte                            VARCHAR NOT NULL,
  altitud_respecto_marr              INTEGER  NOT NULL,
  km_centro_playa                    VARCHAR NOT NULL,
  porcentajes_zv                     VARCHAR NOT NULL,
  bares                              VARCHAR NOT NULL,
  temperatura_rank                   VARCHAR NOT NULL,
  cma_rank                           VARCHAR NOT NULL,
  ipc_rank                           VARCHAR NOT NULL,
  criminalidad_rank                  VARCHAR NOT NULL,
  prof_ap_rank                       VARCHAR NOT NULL,
  cultura_rank                       VARCHAR NOT NULL,
  deporte_rank                       VARCHAR NOT NULL,
  zonas_verdes_rank                  VARCHAR NOT NULL,
  distancia_playa_rank               VARCHAR NOT NULL,
  bares_rank                         VARCHAR NOT NULL,
  CONSTRAINT id_ciudad_ds PRIMARY KEY(id_ciudad)
);
