CREATE TABLE IF NOT EXISTS client(
  id_client int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  names VARCHAR ,
  surname VARCHAR,
  age int,
  gender VARCHAR,
  email VARCHAR,
  job VARCHAR,
  city VARCHAR,
  CONSTRAINT client_pkey PRIMARY KEY(id_client)
);

CREATE TABLE query(
  id_query int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  id_client int,
  salary int,
  qty_rent int,
  like_beach int,
  like_montain int,
  like_hot int,
  like_cold int,
  cost_of_living int,
  health_insurance int,
  outdoor_activities int,
  criminality_preference int,
  CONSTRAINT id_client_fkey FOREIGN KEY(id_client) REFERENCES client(id_client),
  CONSTRAINT id_query_pkey PRIMARY KEY(id_query)
);

CREATE TABLE results(
  id_result int NOT NULL NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  id_query int,
  result varchar,
  CONSTRAINT id_query_fkey FOREIGN KEY(id_query) REFERENCES query(id_query),
  CONSTRAINT id_result_pkey PRIMARY KEY(id_result)
);

CREATE TABLE feedback_results(
  id_fbck_result int NOT NULL NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  id_result int,
  feedback int, 
  CONSTRAINT id_result_fkey FOREIGN KEY(id_result) REFERENCES results(id_result),
  CONSTRAINT id_fbck_result_pkey PRIMARY KEY(id_fbck_result)
);

CREATE TABLE kiribati_dataset(
  id_city INT NOT NULL NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  city                             VARCHAR,
  avg_rent                  INTEGER  NOT NULL,
  idx_ipc                         VARCHAR NOT NULL,
  criminality_rate               DATE  NOT NULL,
  pp_atention               VARCHAR NOT NULL,
  temp                       VARCHAR NOT NULL,
  cultura                            INTEGER  NOT NULL,
  sport                            VARCHAR NOT NULL,
  altitude              INTEGER  NOT NULL,
  km_to_beach                    VARCHAR NOT NULL,
  prcntge_zv                     VARCHAR NOT NULL,
  bars                              VARCHAR NOT NULL,
  temp_rank                   VARCHAR NOT NULL,
  cma_rank                           VARCHAR NOT NULL,
  ipc_rank                           VARCHAR NOT NULL,
  criminality_rank                  VARCHAR NOT NULL,
  prof_ap_rank                       VARCHAR NOT NULL,
  culture_rank                       VARCHAR NOT NULL,
  sports_rank                       VARCHAR NOT NULL,
  green_zone_rank                  VARCHAR NOT NULL,
  km_beach_rank               VARCHAR NOT NULL,
  bars_rank                         VARCHAR NOT NULL,
  CONSTRAINT id_ciudad_ds PRIMARY KEY(id_city)
);
