version: '3'

services:
  mysql:
    image: mysql:5.6
    container_name: docker-mysql
    environment:
      MYSQL_DATABASE: cabin
      MYSQL_USER: cabin
      MYSQL_PASSWORD: cabinpw
      MYSQL_ROOT_PASSWORD: rootpw
    ports:
      - "3306:3306"
    restart: always

  web:
    image: php:7.3-apache
    container_name: docker-php
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
    links:
      - mysql